import {initializeApp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,updateDoc,deleteDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import {firebaseConfig,ADMIN_EMAIL} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=id=>document.getElementById(id),bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
const ok=()=>auth.currentUser&&auth.currentUser.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase();
const users=()=>getDocs(collection(db,"users")).then(s=>s.docs.map(d=>({id:d.id,...d.data()}))),deposits=()=>getDocs(collection(db,"deposits")).then(s=>s.docs.map(d=>({id:d.id,...d.data()})));
async function adminLogin(){try{await signInWithPopup(auth,provider)}catch(e){alert("Admin Login হয়নি: "+e.message)}}window.adminLogin=adminLogin;
async function renderAdminOverview(){if(!ok())return;let [us,ds]=await Promise.all([users(),deposits()]),body=$("adminAccessBody"),monthly=$("adminMonthlyBody"),map={},grand=0,active=0,blocked=0;body.innerHTML="";us.forEach((u,i)=>{let d=ds.filter(x=>x.userId===u.uid),total=d.reduce((s,x)=>s+Number(x.amount||0),0);grand+=total;u.status==="blocked"?blocked++:active++;d.forEach(x=>{let m=(x.date||"").slice(0,7);if(m){map[m]??={count:0,total:0};map[m].count++;map[m].total+=Number(x.amount||0)}});let tr=document.createElement("tr");[bn(i+1),u.gmail||"",u.organizationId||"—",u.organizationName||"—","৳ "+bn(total.toLocaleString("en-US")),d.sort((a,b)=>(b.date||"").localeCompare(a.date||""))[0]?.date||"—",u.status==="blocked"?"Blocked":"Active"].forEach((v,j)=>{let td=document.createElement("td");td.textContent=v;tr.appendChild(td)});let td=document.createElement("td"),b=document.createElement("button");b.textContent="বিস্তারিত";b.onclick=()=>showAdminUser(u.uid);let t=document.createElement("button");t.textContent=u.status==="blocked"?"Unblock":"Block";t.onclick=()=>toggleUser(u.uid,u.status);td.append(b,t);tr.appendChild(td);body.appendChild(tr)});$("adminUserCount").textContent=bn(us.length);$("adminActiveCount").textContent=bn(active);$("adminBlockedCount").textContent=bn(blocked);$("adminGrandTotal").textContent=bn(grand.toLocaleString("en-US"));monthly.innerHTML="";Object.keys(map).sort().reverse().forEach(m=>{let tr=document.createElement("tr");[m,bn(map[m].count),"৳ "+bn(map[m].total.toLocaleString("en-US"))].forEach(v=>{let td=document.createElement("td");td.textContent=v;tr.appendChild(td)});monthly.appendChild(tr)})}
async function showAdminUser(uid){let [us,ds]=await Promise.all([users(),deposits()]),u=us.find(x=>x.uid===uid),d=ds.filter(x=>x.userId===uid).sort((a,b)=>(a.date||"").localeCompare(b.date||""));$("adminSelectedUser").textContent=(u?.gmail||"")+" — "+(u?.name||"");let body=$("adminUserDepositBody");body.innerHTML="";let run=0;d.forEach((x,i)=>{run+=Number(x.amount||0);let tr=document.createElement("tr");[bn(i+1),x.date||"","৳ "+bn(Number(x.amount||0).toLocaleString("en-US")),x.method||"","৳ "+bn(run.toLocaleString("en-US"))].forEach(v=>{let td=document.createElement("td");td.textContent=v;tr.appendChild(td)});body.appendChild(tr)});$("adminUserDepositEmpty").classList.toggle("hidden",!!d.length);$("adminUserDepositWrap").classList.toggle("hidden",!d.length)}
async function toggleUser(uid,status){if(!ok())return;await updateDoc(doc(db,"users",uid),{status:status==="blocked"?"active":"blocked",updatedAt:serverTimestamp()});renderAdminOverview()}window.toggleUser=toggleUser;window.showAdminUser=showAdminUser;
async function saveAdminAccess(){if(!ok())return;let email=$("adminGmail").value.trim().toLowerCase(),us=await users(),u=us.find(x=>x.gmail?.toLowerCase()===email);if(!u)return alert("User আগে User Panel থেকে Google Login করুন।");await updateDoc(doc(db,"users",u.uid),{organizationId:$("adminOrgId").value.trim(),organizationName:$("adminOrgName").value.trim(),status:$("adminActive").value==="true"?"active":"blocked",updatedAt:serverTimestamp()});clearAdminForm();renderAdminOverview();alert("✅ User Access সংরক্ষণ হয়েছে।")}window.saveAdminAccess=saveAdminAccess;
function clearAdminForm(){["adminGmail","adminOrgId","adminOrgName"].forEach(id=>$(id).value="");$("adminActive").value="true"}window.clearAdminForm=clearAdminForm;
async function deleteSelectedUserData(){if(!ok())return;let text=$("adminSelectedUser").textContent,gmail=text.split(" — ")[0].trim();if(!gmail||gmail==="কোনো User নির্বাচন করা হয়নি")return alert("আগে User তালিকা থেকে একজন User নির্বাচন করুন।");if(!confirm(gmail+"\n\nএই User-এর সব তথ্য মুছে ফেলবেন?"))return;let [us,ds]=await Promise.all([users(),deposits()]),u=us.find(x=>x.gmail?.toLowerCase()===gmail.toLowerCase());if(!u)return alert("User পাওয়া যায়নি।");for(const d of ds.filter(x=>x.userId===u.uid))await deleteDoc(doc(db,"deposits",d.id));await deleteDoc(doc(db,"users",u.uid));$("adminSelectedUser").textContent="কোনো User নির্বাচন করা হয়নি";renderAdminOverview();alert("🗑️ User ও তার জমার তথ্য Delete হয়েছে।")}window.deleteSelectedUserData=deleteSelectedUserData;
async function logout(){await signOut(auth);location.reload()}window.logout=logout;window.adminLogout=logout;
function toggleSidebar(){$("sidebar").classList.toggle("open");$("overlay").classList.toggle("show")}window.toggleSidebar=toggleSidebar;function closeSidebar(){$("sidebar").classList.remove("open");$("overlay").classList.remove("show")}window.closeSidebar=closeSidebar;
function showSection(id){["dash","depositForm","depositList","adminPanel"].forEach(x=>$(x)?.classList.add("hidden"));["sideDash","sideForm","sideList","sideAdmin"].forEach(x=>$(x)?.classList.remove("active"));$(id)?.classList.remove("hidden");$(id==="dash"?"sideDash":id==="depositForm"?"sideForm":id==="depositList"?"sideList":"sideAdmin")?.classList.add("active");if(id==="adminPanel")renderAdminOverview();closeSidebar()}window.showSection=showSection;
onAuthStateChanged(auth,async u=>{if(!u)return;if(!ok()){alert("⛔ এই Gmail-এর Admin Access নেই।");return signOut(auth)}$("login").classList.add("hidden");$("app").classList.remove("hidden");$("menuBtn").classList.remove("hidden");await renderAdminOverview();showSection("dash")});
