import {auth,db,provider,signInWithPopup,signOut,onAuthStateChanged,collection,getDocs,doc,updateDoc,setDoc} from "../firebase.js";
const ADMIN_EMAIL="masumbillah6778@gmail.com";let currentUser=null,users=[],allDeposits=[];const $=id=>document.getElementById(id);const bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
window.toggleSidebar=()=>{$("sidebar").classList.toggle("open");$("overlay").classList.toggle("open")};window.closeSidebar=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("open")};window.showSection=id=>{document.querySelectorAll(".page-section").forEach(x=>x.classList.add("hidden"));document.querySelectorAll(".side-link").forEach(x=>x.classList.remove("active"));$(id).classList.remove("hidden");const map={dash:"sideDash",monthly:"sideMonthly",users:"sideUsers"};$(map[id]).classList.add("active");if(id==="dash")renderDash();if(id==="monthly")renderMonthly();if(id==="users")renderUsers();closeSidebar();scrollTo({top:0,behavior:"smooth"})};
async function login(){try{$("loginBtn").disabled=true;await signInWithRedirect(auth,provider)}catch(e){$("status").textContent="Login ব্যর্থ: "+(e?.message||e);$("loginBtn").disabled=false}}window.login=login;
async function load(){users=[];allDeposits=[];const snap=await getDocs(collection(db,"users"));snap.forEach(d=>{const data=d.data();const u={id:d.id,...data,deposits:Array.isArray(data.deposits)?data.deposits:[]};users.push(u);allDeposits.push(...u.deposits.map(x=>({...x,userUid:d.id,userName:u.displayName,userEmail:u.email,memberId:u.memberId})))}) ;renderDash()}
function renderDash(){const active=users.filter(u=>u.active!==false).length;const blocked=users.length-active;const total=allDeposits.reduce((s,x)=>s+Number(x.amount||0),0);$("totalUsers").textContent=bn(users.length);$("activeUsers").textContent=bn(active);$("blockedUsers").textContent=bn(blocked);$("totalSavings").textContent="৳ "+bn(total.toLocaleString("en-US"))}
function renderMonthly(){const map={};allDeposits.forEach(d=>{const m=(d.date||"").slice(0,7);if(!m)return;(map[m]??={count:0,total:0});map[m].count++;map[m].total+=Number(d.amount||0)});$("monthBody").innerHTML=Object.keys(map).sort().reverse().map(m=>`<tr><td>${m}</td><td>${bn(map[m].count)}</td><td>৳ ${bn(map[m].total.toLocaleString("en-US"))}</td></tr>`).join("")||'<tr><td colspan="3">কোনো তথ্য নেই</td></tr>'}
function renderUsers(){$("userBody").innerHTML=users.map((u,i)=>{const t=u.deposits.reduce((s,d)=>s+Number(d.amount||0),0);return `<tr><td>${bn(i+1)}</td><td>${esc(u.memberId||"—")}</td><td><button onclick="details('${u.id}')">${esc(u.displayName||"—")}</button></td><td>${esc(u.email||"—")}</td><td>৳ ${bn(t.toLocaleString("en-US"))}</td><td class="${u.active===false?'status-blocked':'status-active'}">${u.active===false?'🔴 Blocked':'🟢 Active'}</td></tr>`}).join("")||'<tr><td colspan="6">কোনো User পাওয়া যায়নি।</td></tr>'}
window.details=uid=>{const u=users.find(x=>x.id===uid);if(!u)return;$("detail").classList.remove("hidden");$("detailTitle").textContent=(u.displayName||"User")+" — "+(u.memberId||"");$("detailTable").innerHTML='<div class="table-wrap"><table><thead><tr><th>ক্রমিক</th><th>তারিখ</th><th>পরিমাণ</th><th>মাধ্যম</th><th>Action</th></tr></thead><tbody>'+u.deposits.map((d,i)=>`<tr><td>${bn(i+1)}</td><td>${esc(d.date||"")}</td><td>৳ ${bn(Number(d.amount||0).toLocaleString("en-US"))}</td><td>${esc(d.method||"")}</td><td><button onclick="delDeposit('${u.id}','${d.id}')">🗑 Delete</button></td></tr>`).join("")+'</tbody></table></div>'};
window.delDeposit=async(uid,did)=>{if(!confirm("এই জমার তথ্য Delete করবেন?"))return;const u=users.find(x=>x.id===uid);if(!u)return;const next=u.deposits.filter(d=>d.id!==did).map((d,i)=>({...d,serial:i+1}));let total=0;const fixed=next.map(d=>{total+=Number(d.amount||0);return {...d,runningTotal:total}});await updateDoc(doc(db,"users",uid),{deposits:fixed});await load();window.details(uid)};
window.toggleBlock=async uid=>{const u=users.find(x=>x.id===uid);if(!u)return;await updateDoc(doc(db,"users",uid),{active:u.active===false});await load();renderUsers()};
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
window.backup=()=>{const blob=new Blob([JSON.stringify({app:"Money Saving",exportedAt:new Date().toISOString(),users},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="money-saving-backup.json";a.click();URL.revokeObjectURL(a.href)};window.logout=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){$("app").classList.add("hidden");$("login").classList.remove("hidden");$("menuBtn").classList.add("hidden");return}if((user.email||"").toLowerCase()!==ADMIN_EMAIL){alert("এই Google account Admin হিসেবে অনুমোদিত নয়।");await signOut(auth);return}$("login").classList.add("hidden");$("app").classList.remove("hidden");$("menuBtn").classList.remove("hidden");try{await load();showSection("dash")}catch(e){alert("Firebase data load failed: "+(e?.message||e))}});
