import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, updateDoc, deleteDoc, setDoc, writeBatch, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { firebaseConfig, ADMIN_EMAIL } from "./firebase-config.js";

const app=initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app); const provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id); const bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
const isAdmin=()=>auth.currentUser?.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase(); let users=[], deposits=[], selectedUid=null;
const money=n=>"৳ "+bn(Number(n||0).toLocaleString("en-US"));
function esc(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML;}
async function adminLogin(){try{await signInWithPopup(auth,provider)}catch(e){alert("Admin Login হয়নি।\n"+e.message)}} window.adminLogin=adminLogin;
async function loadData(){const [us,ds]=await Promise.all([getDocs(collection(db,"users")),getDocs(collection(db,"deposits"))]);users=us.docs.map(x=>({id:x.id,...x.data()}));deposits=ds.docs.map(x=>({id:x.id,...x.data()}));renderAll();}
function userDeposits(uid){return deposits.filter(d=>d.userId===uid).sort((a,b)=>(a.date||"").localeCompare(b.date||""));}
function userTotal(uid){return userDeposits(uid).reduce((s,d)=>s+Number(d.amount||0),0)}
function renderAll(){renderDashboard();renderUsers();renderMonthly();if(selectedUid)renderDetails(selectedUid)}
function renderDashboard(){const active=users.filter(u=>u.status!=="blocked").length;const blocked=users.length-active;const total=deposits.reduce((s,d)=>s+Number(d.amount||0),0);const now=new Date();const ym=now.toISOString().slice(0,7);const month=deposits.filter(d=>(d.date||"").slice(0,7)===ym).reduce((s,d)=>s+Number(d.amount||0),0);$("totalUsers").textContent=bn(users.length);$("activeUsers").textContent=bn(active);$("blockedUsers").textContent=bn(blocked);$("totalSavings").textContent=money(total);$("totalDeposits").textContent=bn(deposits.length);$("currentMonth").textContent=money(month)}
function renderUsers(){const body=$("usersBody"),q=($("userSearch")?.value||"").toLowerCase().trim();body.innerHTML="";const list=users.filter(u=>[u.name,u.gmail,u.memberId,u.uid].some(v=>String(v||"").toLowerCase().includes(q))).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),"bn"));$("usersEmpty").classList.toggle("hidden",list.length>0);$("usersWrap").classList.toggle("hidden",list.length===0);list.forEach((u,i)=>{const ds=userDeposits(u.uid);const tr=document.createElement("tr");[bn(i+1),u.memberId||"—",u.name||"—",u.gmail||"—",money(ds.reduce((s,d)=>s+Number(d.amount||0),0)),u.status==="blocked"?"🔴 Blocked":"🟢 Active"].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)});const a=document.createElement("td");[['📊 বিস্তারিত',()=>showUserDetails(u.uid)],['✏️ Edit',()=>editUser(u.uid)], [u.status==='blocked'?'🔓 Unblock':'🔒 Block',()=>toggleUser(u.uid)],['🗑️ Delete',()=>deleteUser(u.uid)]].forEach(([t,fn])=>{const b=document.createElement('button');b.className='small-btn';b.textContent=t;b.onclick=fn;a.appendChild(b)});tr.appendChild(a);body.appendChild(tr)})}
window.renderUsers=renderUsers;
function renderMonthly(){const map={};deposits.forEach(d=>{const m=(d.date||"").slice(0,7);if(!m)return;(map[m]??={count:0,total:0}).count++;map[m].total+=Number(d.amount||0)});const body=$("monthlyBody");body.innerHTML="";const months=Object.keys(map).sort().reverse();$("monthlyEmpty").classList.toggle('hidden',months.length>0);$("monthlyWrap").classList.toggle('hidden',months.length===0);months.forEach(m=>{const tr=document.createElement('tr');[m,bn(map[m].count),money(map[m].total)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});body.appendChild(tr)})}
function showUserDetails(uid){selectedUid=uid;showSection('users');renderDetails(uid)} window.showUserDetails=showUserDetails;
function renderDetails(uid){const u=users.find(x=>x.uid===uid);if(!u)return;$("detailCard").classList.remove('hidden');$("selectedUser").textContent=`${u.name||'—'} — ${u.memberId||'—'} — ${u.gmail||'—'}`;const body=$("detailBody");body.innerHTML='';let run=0;userDeposits(uid).forEach((d,i)=>{run+=Number(d.amount||0);const tr=document.createElement('tr');[bn(i+1),d.date||'—',money(d.amount),d.method||'—',money(run)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});body.appendChild(tr)});$("detailTotal").textContent=money(run)}
function editUser(uid){const u=users.find(x=>x.uid===uid);if(!u)return;selectedUid=uid;$("editUid").value=u.uid;$("editMemberId").value=u.memberId||'';$("editName").value=u.name||'';$("editGmail").value=u.gmail||'';$("editStatus").value=u.status==='blocked'?'blocked':'active';$("editModal").classList.add('show')} window.editUser=editUser;
window.closeEdit=()=>$("editModal").classList.remove('show');
$("editForm")?.addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return;const uid=$("editUid").value;try{await updateDoc(doc(db,'users',uid),{name:$("editName").value.trim(),memberId:$("editMemberId").value.trim(),status:$("editStatus").value,updatedAt:serverTimestamp()});await loadData();closeEdit();alert('✅ User তথ্য আপডেট হয়েছে।')}catch(e){alert('❌ আপডেট হয়নি।\n'+e.message)}});
async function toggleUser(uid){if(!isAdmin())return;const u=users.find(x=>x.uid===uid);if(!u)return;const next=u.status==='blocked'?'active':'blocked';if(!confirm(`${u.name||u.gmail}\n\n${next==='blocked'?'Block':'Unblock'} করবেন?`))return;try{await updateDoc(doc(db,'users',uid),{status:next,updatedAt:serverTimestamp()});await loadData();alert(next==='blocked'?'🔒 User Block করা হয়েছে।':'✅ User Unblock হয়েছে।')}catch(e){alert('❌ Status পরিবর্তন হয়নি।\n'+e.message)}} window.toggleUser=toggleUser;
async function deleteUser(uid){if(!isAdmin())return;const u=users.find(x=>x.uid===uid);if(!u)return;const ds=userDeposits(uid);if(!confirm(`${u.name||u.gmail}\n\nএই User-এর account এবং ${ds.length}টি জমার তথ্য স্থায়ীভাবে Delete করবেন?\nএই কাজ Undo করা যাবে না।`))return;try{let batch=writeBatch(db);batch.delete(doc(db,'users',uid));ds.forEach(d=>batch.delete(doc(db,'deposits',d.id)));await batch.commit();selectedUid=null;$("detailCard").classList.add('hidden');await loadData();alert('🗑️ User এবং তার জমার তথ্য Delete হয়েছে।')}catch(e){alert('❌ Delete হয়নি।\n'+e.message)}} window.deleteUser=deleteUser;
function exportBackup(){const payload={version:1,exportedAt:new Date().toISOString(),users,deposits};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`money-saving-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)} window.exportBackup=exportBackup;
async function restoreBackup(file){if(!isAdmin()||!file)return;try{const text=await file.text(),data=JSON.parse(text);if(!Array.isArray(data.users)||!Array.isArray(data.deposits))throw Error('সঠিক Money-Saving backup নয়।');if(!confirm(`Backup-এ ${data.users.length} User এবং ${data.deposits.length} Deposit আছে।\n\nএকই ID-এর ডাটা overwrite/restore করা হবে। চালাবেন?`))return;for(let i=0;i<data.users.length;i+=400){const b=writeBatch(db);data.users.slice(i,i+400).forEach(u=>{const id=u.uid||u.id;if(id)b.set(doc(db,'users',id),u,{merge:true})});await b.commit()}for(let i=0;i<data.deposits.length;i+=400){const b=writeBatch(db);data.deposits.slice(i,i+400).forEach(d=>{const id=d.id;if(id)b.set(doc(db,'deposits',id),d,{merge:true})});await b.commit()}await loadData();alert('✅ Backup Restore সম্পন্ন হয়েছে।')}catch(e){alert('❌ Restore হয়নি।\n'+e.message)}} window.restoreBackup=restoreBackup;
function printReport(){window.print()} window.printReport=printReport;
function showSection(id){['dash','monthly','users'].forEach(x=>$(x).classList.add('hidden'));['sideDash','sideMonthly','sideUsers'].forEach(x=>$(x).classList.remove('active'));$(id).classList.remove('hidden');$(id==='dash'?'sideDash':id==='monthly'?'sideMonthly':'sideUsers').classList.add('active');closeSidebar()} window.showSection=showSection;
function toggleSidebar(){$('sidebar').classList.toggle('open');$('overlay').classList.toggle('show')}function closeSidebar(){$('sidebar').classList.remove('open');$('overlay').classList.remove('show')}window.toggleSidebar=toggleSidebar;window.closeSidebar=closeSidebar;
async function logout(){await signOut(auth);location.reload()}window.logout=logout;
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeEdit()});
onAuthStateChanged(auth,async user=>{if(!user){$('login').classList.remove('hidden');$('app').classList.add('hidden');$('menuBtn').classList.add('hidden');return}if(!isAdmin()){alert('⛔ এই Gmail-এর Admin Access নেই।');await signOut(auth);return}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('menuBtn').classList.remove('hidden');try{await loadData();showSection('dash')}catch(e){alert('Admin data load হয়নি।\n'+e.message)}});
