import {initializeApp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,collection,addDoc,getDocs,query,where,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id),bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
const uid=()=>auth.currentUser.uid;
function mid(x){let h=0;for(const c of x)h=(h*31+c.charCodeAt(0))>>>0;return "6778"+String(h%10000+1).padStart(4,"0")}
async function getUser(){let s=await getDoc(doc(db,"users",uid()));return s.exists()?s.data():null}
async function login(){try{await signInWithPopup(auth,provider)}catch(e){alert("Google Login হয়নি: "+e.message)}}window.login=login;
async function save(){let name=$("name").value.trim();if(!name)return alert("দয়া করে আপনার নাম লিখুন।");let old=await getUser();await setDoc(doc(db,"users",uid()),{uid:uid(),gmail:auth.currentUser.email.toLowerCase(),memberId:old?.memberId||mid(uid()),name,status:old?.status||"active",updatedAt:serverTimestamp()},{merge:true});showDashboard()}window.save=save;
async function deps(){let s=await getDocs(query(collection(db,"deposits"),where("userId","==",uid())));return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.date||"").localeCompare(b.date||""))}
async function showDashboard(){let u=await getUser();if(!u)return;if(u.status==="blocked"){await signOut(auth);return alert("🔒 আপনার User ID বর্তমানে Block করা হয়েছে।")}$("login").classList.add("hidden");$("setup").classList.add("hidden");$("app").classList.remove("hidden");$("showName").textContent=u.name||"User";renderDeposits()}
async function openDepositForm(){let u=await getUser(),d=await deps();$("serial").value=d.length+1;$("memberId").value=u.memberId;$("memberName").value=u.name;$("depositDate").value=new Date().toISOString().slice(0,10);$("depositAmount").value="";$("depositMethod").value="";$("depositForm").classList.remove("hidden")}window.openDepositForm=openDepositForm;
window.closeDepositForm=()=>$("depositForm").classList.add("hidden");
async function saveDeposit(){let u=await getUser();if(u.status==="blocked")return alert("🔒 আপনার User ID Block করা হয়েছে।");let date=$("depositDate").value,amount=Number($("depositAmount").value),method=$("depositMethod").value;if(!date)return alert("জমার তারিখ নির্বাচন করুন।");if(amount<=0||!Number.isFinite(amount))return alert("সঠিক জমার পরিমাণ লিখুন।");if(!method)return alert("জমার মাধ্যম নির্বাচন করুন।");let d=await deps(),total=d.reduce((s,x)=>s+Number(x.amount||0),0)+amount;await addDoc(collection(db,"deposits"),{userId:uid(),memberId:u.memberId,name:u.name,userEmail:u.gmail,date,amount,method,serial:d.length+1,runningTotal:total,createdAt:serverTimestamp()});$("depositForm").classList.add("hidden");await renderDeposits();alert("✅ টাকা জমার তথ্য সফলভাবে সংরক্ষণ হয়েছে।")}window.saveDeposit=saveDeposit;
async function renderDeposits(){let d=await deps(),total=d.reduce((s,x)=>s+Number(x.amount||0),0);$("totalAmount").textContent=bn(total.toLocaleString("en-US"));$("totalCount").textContent=bn(d.length);let body=$("depositBody");body.innerHTML="";$("depositEmpty").classList.toggle("hidden",!!d.length);$("depositTableWrap").classList.toggle("hidden",!d.length);let run=0;d.forEach((x,i)=>{run+=Number(x.amount||0);let tr=document.createElement("tr");[bn(i+1),x.memberId||"",x.date||"","৳ "+bn(Number(x.amount||0).toLocaleString("en-US")),x.method||"","৳ "+bn(run.toLocaleString("en-US"))].forEach(v=>{let td=document.createElement("td");td.textContent=v;tr.appendChild(td)});body.appendChild(tr)})}
async function logout(){await signOut(auth);location.reload()}window.logout=logout;
onAuthStateChanged(auth,async u=>{if(!u)return;let d=await getUser();if(d?.name)showDashboard();else{$("login").classList.add("hidden");$("setup").classList.remove("hidden")}});
