import {auth,db,provider,signInWithPopup,signOut,onAuthStateChanged,doc,getDoc,setDoc,serverTimestamp} from "../firebase.js";
let currentUser=null, profile=null, deposits=[];
const $=id=>document.getElementById(id);
const bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
function setStatus(msg,error=false){const el=$("status");if(el){el.textContent=msg||"";el.className="status"+(error?" error":"");}}
function closeSidebar(){$("sidebar")?.classList.remove("open");$("overlay")?.classList.remove("open")}
window.closeSidebar=closeSidebar;window.toggleSidebar=()=>{$("sidebar")?.classList.toggle("open");$("overlay")?.classList.toggle("open")};
window.showSection=id=>{document.querySelectorAll(".page-section").forEach(x=>x.classList.add("hidden"));document.querySelectorAll(".side-link").forEach(x=>x.classList.remove("active"));$(id)?.classList.remove("hidden");const map={dash:"sideDash",depositForm:"sideForm",depositList:"sideList"};if(map[id])$(map[id])?.classList.add("active");if(id==="depositForm")openDepositForm();if(id==="depositList")renderTable();closeSidebar();scrollTo({top:0,behavior:"smooth"})};
async function login(){const btn=$("googleBtn");try{btn.disabled=true;btn.textContent="⏳ Google Login হচ্ছে...";setStatus("Google account নির্বাচন করুন...");await signInWithPopup(auth,provider)}catch(e){console.error(e);let m=e?.message||String(e);if(e?.code==="auth/popup-blocked")m="Chrome popup বন্ধ করেছে। উপরের Pop-up blocked বার্তায় Always show দিন, তারপর আবার Login করুন।";if(e?.code==="auth/unauthorized-domain")m="এই GitHub domain Firebase Authentication-এর Authorized domains-এ যোগ করুন।";if(e?.code==="auth/operation-not-allowed")m="Firebase Console-এ Google Sign-in চালু করুন।";setStatus("❌ "+m,true);btn.disabled=false;btn.textContent="🔵 Google দিয়ে Login"}}window.login=login;
async function ensureProfile(){const ref=doc(db,"users",currentUser.uid);setStatus("Firebase User profile লোড হচ্ছে...");const snap=await getDoc(ref);if(snap.exists()){profile={uid:currentUser.uid,...snap.data()};deposits=Array.isArray(profile.deposits)?profile.deposits:[];if(profile.active===false)throw new Error("এই User বর্তমানে Block করা হয়েছে।");return}const id="6778"+currentUser.uid.replace(/[^0-9]/g,"").slice(0,6).padStart(6,"0");profile={uid:currentUser.uid,memberId:id,displayName:"",email:(currentUser.email||"").toLowerCase(),active:true,deposits:[],createdAt:serverTimestamp()};await setDoc(ref,profile);deposits=[]}
async function saveProfile(patch){profile={...profile,...patch};await setDoc(doc(db,"users",currentUser.uid),patch,{merge:true})}
function updateDashboard(){const total=deposits.reduce((s,x)=>s+Number(x.amount||0),0);$("totalAmount").textContent=bn(total.toLocaleString("en-US"));$("totalCount").textContent=bn(deposits.length)}
function renderTable(){const body=$("tbody");if(!body)return;body.innerHTML="";$("empty")?.classList.toggle("hidden",deposits.length>0);$("tableWrap")?.classList.toggle("hidden",deposits.length===0);deposits.forEach((x,i)=>{const tr=document.createElement("tr");[bn(i+1),x.memberId||profile.memberId,x.date||"","৳ "+Number(x.amount||0).toLocaleString("en-US"),x.method||""].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)});body.appendChild(tr)})}
function openDepositForm(){$("serial").value=bn(deposits.length+1);$("memberId").value=profile.memberId;$("memberName").value=profile.displayName;$("depositDate").value=new Date().toISOString().slice(0,10);$("depositAmount").value="";$("depositMethod").value=""}
window.openDepositForm=openDepositForm;
window.saveName=async()=>{try{const name=$("name").value.trim();if(!name)return alert("দয়া করে আপনার নাম লিখুন।");await saveProfile({displayName:name});await showApp()}catch(e){alert("নাম সংরক্ষণ করা যায়নি:\n\n"+e.message)}};
async function saveDeposit(){const date=$("depositDate").value,amount=Number($("depositAmount").value),method=$("depositMethod").value;if(!date)return alert("জমার তারিখ নির্বাচন করুন।");if(!Number.isFinite(amount)||amount<=0)return alert("সঠিক জমার পরিমাণ লিখুন।");if(!method)return alert("জমার মাধ্যম নির্বাচন করুন।");const previous=deposits.reduce((s,x)=>s+Number(x.amount||0),0);const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),serial:deposits.length+1,memberId:profile.memberId,name:profile.displayName,date,amount,method,runningTotal:previous+amount,ownerUid:currentUser.uid,ownerEmail:(currentUser.email||"").toLowerCase(),createdAt:new Date().toISOString()};const next=[...deposits,item];try{await setDoc(doc(db,"users",currentUser.uid),{deposits:next},{merge:true});deposits=next;profile.deposits=next;updateDashboard();renderTable();$("depositAmount").value="";$("depositMethod").value="";alert("✅ টাকা অনলাইনে সফলভাবে সংরক্ষণ হয়েছে।");showSection("dash")}catch(e){alert("তথ্য সংরক্ষণ করা যায়নি:\n\n"+e.message)}}window.saveDeposit=saveDeposit;
async function showApp(){$("login").classList.add("hidden");$("setup").classList.add("hidden");$("app").classList.remove("hidden");$("menuBtn").classList.remove("hidden");$("showName").textContent=profile.displayName;$("memberIdShow").textContent=profile.memberId;renderTable();updateDashboard();showSection("dash")}
function showSetup(){$("login").classList.add("hidden");$("setup").classList.remove("hidden");$("name").value=profile.displayName||"";$("name").focus()}
window.logout=async()=>{try{await signOut(auth)}catch(e){console.error(e)}};
window.addEventListener("DOMContentLoaded",()=>{$("googleBtn")?.addEventListener("click",login);setStatus("Firebase Login প্রস্তুত আছে।")});
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){$("app").classList.add("hidden");$("setup").classList.add("hidden");$("login").classList.remove("hidden");$("menuBtn").classList.add("hidden");closeSidebar();return}try{await ensureProfile();if(!profile.displayName)showSetup();else await showApp()}catch(e){console.error(e);let m=e?.message||String(e);if(e?.code==="permission-denied")m="Firestore permission denied. Firebase Console-এর নতুন firestore.rules হুবহু Publish করুন।";setStatus("❌ "+m,true);alert("User data load failed:\n\n"+m);try{await signOut(auth)}catch(_){} }});
