import { auth, db, provider, signInWithPopup, signOut, onAuthStateChanged } from "../firebase.js";
import { doc, getDoc, setDoc, collection, addDoc, getDocs, query, orderBy, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";

const $=id=>document.getElementById(id); let currentUser=null, profile=null, deposits=[];
const bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]); const money=n=>Number(n||0).toLocaleString("en-US");
function toast(t){$("toast").textContent=t;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),1800)}
window.toggleSidebar=()=>{$("sidebar").classList.toggle("open");$("overlay").classList.toggle("hidden")}; window.closeSidebar=()=>{$("sidebar").classList.remove("open");$("overlay").classList.add("hidden")};
window.showSection=id=>{["dashboard","depositForm","depositList"].forEach(x=>$(x).classList.toggle("hidden",x!==id));["sideDash","sideForm","sideList"].forEach(x=>$(x).classList.remove("active"));({dashboard:"sideDash",depositForm:"sideForm",depositList:"sideList"})[id]&&$( ({dashboard:"sideDash",depositForm:"sideForm",depositList:"sideList"})[id]).classList.add("active");if(id==="depositForm")openForm();if(id==="depositList")render();closeSidebar();window.scrollTo({top:0,behavior:"smooth"})};
window.login=async()=>{const b=$("googleBtn");b.disabled=true;b.textContent="⏳ Google Login হচ্ছে...";try{await signInWithPopup(auth,provider)}catch(e){console.error(e);$("loginMsg").textContent="Login হয়নি: "+(e.code||e.message)}finally{b.disabled=false;b.textContent="🔵 Sign in with Google"}};
window.saveName=async()=>{const name=$("displayName").value.trim();if(!name)return alert("দয়া করে আপনার নাম লিখুন।");if(!currentUser)return;try{if(!profile.memberId)profile=await createProfile(name);else{profile.name=name;await setDoc(doc(db,"users",currentUser.uid),{name,updatedAt:serverTimestamp()},{merge:true})}showApp();toast("✅ নাম সংরক্ষণ হয়েছে")}catch(e){alert("নাম সংরক্ষণ হয়নি: "+e.message)}};
async function createProfile(name){return await runTransaction(db,async tx=>{const userRef=doc(db,"users",currentUser.uid), counterRef=doc(db,"meta","memberCounter");const u=await tx.get(userRef), c=await tx.get(counterRef);if(u.exists()&&u.data().memberId)return u.data();let next=c.exists()?Number(c.data().next||1):1;const memberId="6778"+String(next).padStart(4,"0");const data={name,memberId,memberNo:next,email:currentUser.email.toLowerCase(),role:"user",active:true,createdAt:serverTimestamp()};tx.set(userRef,data,{merge:true});tx.set(counterRef,{next:next+1},{merge:true});return {...data}})}
async function loadProfile(){const s=await getDoc(doc(db,"users",currentUser.uid));profile=s.exists()?s.data():null;if(profile?.active===false){alert("আপনার User Access বর্তমানে বন্ধ আছে।");await signOut(auth);return false}return true}
async function loadDeposits(){const q=query(collection(db,"users",currentUser.uid,"deposits"),orderBy("date","asc"));const s=await getDocs(q);deposits=s.docs.map(d=>({id:d.id,...d.data()}));}
function showApp(){$("loginScreen").classList.add("hidden");$("nameScreen").classList.add("hidden");$("app").classList.remove("hidden");$("menuBtn").classList.remove("hidden");$("showName").textContent=profile?.name||"User";$("showMemberId").textContent=profile?.memberId||"—";$("sideUser").textContent=profile?.name||"Money Saving";render();window.showSection("dashboard")}
function render(){const total=deposits.reduce((s,d)=>s+Number(d.amount||0),0);$("totalAmount").textContent=bn(money(total));$("totalCount").textContent=bn(deposits.length);$("lastDate").textContent=deposits.length?deposits[deposits.length-1].date:"—";const body=$("depositBody");body.innerHTML="";if(!deposits.length){$("empty").classList.remove("hidden");$("tableWrap").classList.add("hidden");return}$("empty").classList.add("hidden");$("tableWrap").classList.remove("hidden");let running=0;deposits.forEach((d,i)=>{running+=Number(d.amount||0);const tr=document.createElement("tr");[bn(i+1),profile.memberId,d.date,"৳ "+money(d.amount),d.method,"৳ "+money(running)].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)});body.appendChild(tr)})}
function openForm(){$("serial").value=deposits.length+1;$("memberId").value=profile?.memberId||"";$("memberName").value=profile?.name||"";$("depositDate").value=new Date().toISOString().slice(0,10);$("depositAmount").value="";$("depositMethod").value=""}
window.openForm=openForm;window.saveDeposit=async()=>{const date=$("depositDate").value,amount=Number($("depositAmount").value),method=$("depositMethod").value;if(!date||!amount||amount<=0||!method)return alert("তারিখ, পরিমাণ ও জমার মাধ্যম সঠিকভাবে পূরণ করুন।");try{await addDoc(collection(db,"users",currentUser.uid,"deposits"),{serial:deposits.length+1,memberId:profile.memberId,name:profile.name,date,amount,method,createdAt:serverTimestamp()});await loadDeposits();render();toast("✅ টাকা জমা অনলাইনে সংরক্ষণ হয়েছে");window.showSection("depositForm");}catch(e){alert("সংরক্ষণ ব্যর্থ: "+e.message)}};
window.logoutUser=async()=>{if(!confirm("Logout করতে চান?"))return;await signOut(auth)};
onAuthStateChanged(auth,async u=>{currentUser=u;if(!u){$("app").classList.add("hidden");$("nameScreen").classList.add("hidden");$("loginScreen").classList.remove("hidden");$("menuBtn").classList.add("hidden");return}try{if(!(await loadProfile()))return;if(!profile){$("loginScreen").classList.add("hidden");$("nameScreen").classList.remove("hidden");$("menuBtn").classList.remove("hidden");return}await loadDeposits();showApp()}catch(e){console.error(e);alert("ডাটা লোড হয়নি: "+e.message)}});
