import { auth, db, provider, signInWithPopup, signOut, onAuthStateChanged } from "../firebase.js";
import { doc, getDoc, getDocs, collection, query, orderBy, updateDoc, deleteDoc, writeBatch } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
let admin=null, users=[]; const $=id=>document.getElementById(id); const bn=n=>String(n).replace(/[0-9]/g,d=>"০১২৩৪৫৬৭৮৯"[d]); const money=n=>Number(n||0).toLocaleString("en-US");
$("loginBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){$("msg").textContent="Login হয়নি: "+e.message}};
async function isAdmin(u){const s=await getDoc(doc(db,"users",u.uid));return s.exists()&&s.data().role==="admin"}
async function start(u){if(!(await isAdmin(u))){$("msg").textContent="⛔ এই Google account-এর Admin অনুমতি নেই।";await signOut(auth);return}admin=u;$("gate").classList.add("hidden");$("panel").classList.remove("hidden");await loadUsers()}
window.loadUsers=async()=>{users=[];const snap=await getDocs(collection(db,"users"));for(const d of snap.docs){const u={uid:d.id,...d.data()};if(u.role!=="admin")users.push(u)}let active=0,blocked=0,total=0;for(const u of users){const ds=await getDocs(collection(db,"users",u.uid,"deposits"));u.deposits=ds.docs.map(x=>({id:x.id,...x.data()}));u.total=u.deposits.reduce((s,d)=>s+Number(d.amount||0),0);total+=u.total;if(u.active===false)blocked++;else active++}$("totalUsers").textContent=bn(users.length);$("activeUsers").textContent=bn(active);$("blockedUsers").textContent=bn(blocked);$("grandTotal").textContent="৳ "+money(total);const b=$("usersBody");b.innerHTML="";users.forEach((u,i)=>{const tr=document.createElement("tr");[bn(i+1),u.memberId||"—",u.name||"—",u.email||"—","৳ "+money(u.total)].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)});const st=document.createElement("td");st.innerHTML=`<span class="badge ${u.active===false?"blocked-badge":"active-badge"}">${u.active===false?"🔴 Blocked":"🟢 Active"}</span>`;tr.appendChild(st);const ac=document.createElement("td"),bt=document.createElement("button");bt.className="btn btn-secondary";bt.textContent="📊 বিস্তারিত";bt.onclick=()=>showDetail(u.uid);ac.appendChild(bt);tr.appendChild(ac);b.appendChild(tr)})};
async function showDetail(uid){const u=users.find(x=>x.uid===uid);if(!u)return;$("detail").classList.remove("hidden");$("detailTitle").textContent=`${u.name||"User"} — ${u.memberId||""}`;$("blockBtn").textContent=u.active===false?"🔓 Unblock":"🔒 Block";$("blockBtn").onclick=async()=>{await updateDoc(doc(db,"users",uid),{active:u.active===false});await loadUsers();await showDetail(uid)};$("deleteUserBtn").onclick=async()=>{if(!confirm("এই User-এর সকল জমার তথ্য ও User profile Delete করবেন?"))return;const batch=writeBatch(db);for(const d of u.deposits)batch.delete(doc(db,"users",uid,"deposits",d.id));batch.delete(doc(db,"users",uid));await batch.commit();closeDetail();await loadUsers()};const b=$("depBody");b.innerHTML="";let running=0;u.deposits.sort((a,b)=>(a.date||"").localeCompare(b.date||"")).forEach((d,i)=>{running+=Number(d.amount||0);const tr=document.createElement("tr");[bn(i+1),d.date||"—","৳ "+money(d.amount),d.method||"—","৳ "+money(running)].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)});const td=document.createElement("td"),bt=document.createElement("button");bt.className="btn btn-danger";bt.textContent="Delete";bt.onclick=async()=>{if(!confirm("এই জমা মুছে ফেলবেন?"))return;await deleteDoc(doc(db,"users",uid,"deposits",d.id));await loadUsers();showDetail(uid)};td.appendChild(bt);tr.appendChild(td);b.appendChild(tr)})}
window.showDetail=showDetail;window.closeDetail=()=>$("detail").classList.add("hidden");window.adminLogout=()=>signOut(auth);onAuthStateChanged(auth,u=>{if(u)start(u);else{$("gate").classList.remove("hidden");$("panel").classList.add("hidden")}});
